name: Deploy to ECS

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ECR
      run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 471112942844.dkr.ecr.ap-northeast-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t test-rails-mysql .
        docker tag test-rails-mysql:latest 471112942844.dkr.ecr.ap-northeast-1.amazonaws.com/test-rails-mysql:latest
        docker push 471112942844.dkr.ecr.ap-northeast-1.amazonaws.com/test-rails-mysql:latest

    - name: Update ECS service
      run: aws ecs update-service --cluster rails-mysql-cluster --service rails-mysql-service --force-new-deployment

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
